#!/bin/bash

# Frontend Configuration Script
# This script helps configure the frontend to connect to the correct backend

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    local color=$1
    local message=$2
    echo -e "${color}[$(date '+%Y-%m-%d %H:%M:%S')] ${message}${NC}"
}

# Function to print help
print_help() {
    echo "Frontend Configuration Script"
    echo ""
    echo "Usage:"
    echo "  $0 [backend-ip] [-h|--help]"
    echo ""
    echo "Options:"
    echo "  backend-ip    IP address of the backend server (default: localhost)"
    echo "  -h, --help    Show this help message"
    echo ""
    echo "Examples:"
    echo "  $0                    # Configure for localhost backend"
    echo "  $0 192.168.10.5      # Configure for remote backend"
    echo ""
}

# Default backend IP
BACKEND_IP="localhost"

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            print_help
            exit 0
            ;;
        *)
            BACKEND_IP="$1"
            shift
            ;;
    esac
done

print_status $BLUE "Configuring frontend for backend: $BACKEND_IP"

# Create .env.local file
ENV_FILE="ui/.env.local"
cat > "$ENV_FILE" << EOF
# Frontend Environment Configuration
# Generated by configure-frontend.sh

# Backend API Configuration
VITE_API_BASE_URL=http://$BACKEND_IP:8000
EOF

print_status $GREEN "Created $ENV_FILE with backend URL: http://$BACKEND_IP:8000"

# Test backend connectivity
print_status $BLUE "Testing backend connectivity..."
if curl -s "http://$BACKEND_IP:8000/health" > /dev/null; then
    print_status $GREEN "Backend is accessible at http://$BACKEND_IP:8000"
else
    print_status $RED "Warning: Backend is not accessible at http://$BACKEND_IP:8000"
    print_status $YELLOW "Please check:"
    print_status $YELLOW "  1. Backend is running"
    print_status $YELLOW "  2. IP address is correct"
    print_status $YELLOW "  3. Network connectivity"
fi

print_status $GREEN "Frontend configuration complete!"
print_status $BLUE "Next steps:"
print_status $BLUE "  1. Restart the frontend: cd ui && npm run dev"
print_status $BLUE "  2. Open browser and test the application"
print_status $BLUE "  3. Check browser console for any errors"


