#!/bin/bash

# Corporate Environment Frontend Configuration Script
# This script helps bypass corporate security caching issues

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Function to print colored output
print_status() {
    local color=$1
    local message=$2
    echo -e "${color}[$(date '+%Y-%m-%d %H:%M:%S')] ${message}${NC}"
}

# Function to print help
print_help() {
    echo "Corporate Environment Frontend Configuration Script"
    echo ""
    echo "Usage:"
    echo "  $0 [backend-ip] [port] [protocol] [-h|--help]"
    echo ""
    echo "Options:"
    echo "  backend-ip    IP address of the backend server (default: localhost)"
    echo "  port          Port number (default: 8000)"
    echo "  protocol      Protocol: http or https (default: http)"
    echo "  -h, --help    Show this help message"
    echo ""
    echo "Examples:"
    echo "  $0                           # Configure for localhost:8000"
    echo "  $0 192.168.10.5             # Configure for remote backend"
    echo "  $0 192.168.10.5 8001        # Use different port to bypass cache"
    echo "  $0 192.168.10.5 8000 https  # Use HTTPS to bypass cache"
    echo ""
}

# Default values
BACKEND_IP="localhost"
PORT="8000"
PROTOCOL="http"

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        -h|--help)
            print_help
            exit 0
            ;;
        *)
            if [[ -z "$BACKEND_IP" || "$BACKEND_IP" == "localhost" ]]; then
                BACKEND_IP="$1"
            elif [[ -z "$PORT" || "$PORT" == "8000" ]]; then
                PORT="$1"
            elif [[ -z "$PROTOCOL" || "$PROTOCOL" == "http" ]]; then
                PROTOCOL="$1"
            fi
            shift
            ;;
    esac
done

# Validate protocol
if [[ "$PROTOCOL" != "http" && "$PROTOCOL" != "https" ]]; then
    print_status $RED "Error: Protocol must be 'http' or 'https'"
    exit 1
fi

BACKEND_URL="${PROTOCOL}://${BACKEND_IP}:${PORT}"

print_status $BLUE "Configuring frontend for corporate environment"
print_status $BLUE "Backend URL: $BACKEND_URL"

# Create .env.local file
ENV_FILE="ui/.env.local"
cat > "$ENV_FILE" << EOF
# Frontend Environment Configuration
# Generated by configure-corporate-frontend.sh
# Corporate environment bypass configuration

# Backend API Configuration
VITE_API_BASE_URL=$BACKEND_URL
EOF

print_status $GREEN "Created $ENV_FILE with backend URL: $BACKEND_URL"

# Test backend connectivity
print_status $BLUE "Testing backend connectivity..."
if curl -s -k "$BACKEND_URL/health" > /dev/null; then
    print_status $GREEN "Backend is accessible at $BACKEND_URL"
else
    print_status $RED "Warning: Backend is not accessible at $BACKEND_URL"
    print_status $YELLOW "Please check:"
    print_status $YELLOW "  1. Backend is running"
    print_status $YELLOW "  2. IP address and port are correct"
    print_status $YELLOW "  3. Network connectivity"
    print_status $YELLOW "  4. Corporate firewall settings"
fi

print_status $GREEN "Corporate frontend configuration complete!"
print_status $BLUE "Next steps:"
print_status $BLUE "  1. Restart the frontend: cd ui && npm run dev"
print_status $BLUE "  2. Open browser and test the application"
print_status $BLUE "  3. If still cached, try:"
print_status $BLUE "     - Different port (e.g., 8001, 8002)"
print_status $BLUE "     - HTTPS instead of HTTP"
print_status $BLUE "     - Different browser or incognito mode"
print_status $BLUE "     - Clear corporate proxy cache (contact IT)"
print_status $BLUE "  4. Check browser console for any errors"


